### ISSUE TITLE
Tooltips to explain how each parameter affects the total score

### ISSUE THREAD

**Issue by Buccaneer** [oSoc17/oasis-frontend#177]
For every parameter (avg delay, hops, frequence, ...) we need a tooltip that gives further information about the parameter itself as well as information about how much it contributes to the total score.

**Comment by robrechtme** [comment]
Tooltips bloat the EventListeners on the score page, chrome crashes when I try to add tooltips

**Comment by Buccaneer** [comment]
See #285 before we can solve this issue.
