### ISSUE TITLE
implement caching

### ISSUE THREAD

**Issue by DeMoorJasper** [oSoc17/oasis-frontend#3]

**Comment by pietercolpaert** [comment]
Caching is done by your browser, right? You don't need to do it yourself?

**Comment by DeMoorJasper** [comment]
Caching of data we pull from the linked connections server isn't cached by the browser i think? I might be completely wrong.
It also removes the moment angular triggers a routing event, i tried solve that with saving it in localstorage but i think that's sort of a hacky solution

**Comment by DeMoorJasper** [comment]
Browser does this
